# Member specific settings
ARCHIVE="${ARCHIVE}/mbr000/"
BDDIR="$BDDIR"
CLIMDIR="$CLIMDIR/mbr000"
ENSBDMBR="0"
ENSCTL="000"
EXTRARCH="${EXTRARCH}/${OBSMON_EXP}/mbr000/"
LL_LIST="24,3"
LSMIXBC="yes"
OBDIR="$OBDIR"
PERTATMO="none"
PERTSURF="none"
VFLDEXP="${EXP}mbr000"
XRIMAX="0.2"
# End of member specific settings
